using System.Collections.Generic;

namespace MIDILibrary
{
    public class MidiConstants
    {
        public static readonly uint MIDI_SIGNATURE = 0x4D546864;
        public static readonly uint TRACK_SIGNATURE = 0x4D54726B;
        public static readonly byte META_EVENT = 0xFF;
        public static readonly byte SYSEX_EVENT = 0xF0;
        public static readonly byte END_OF_TRACK = 0x2F;
        public static readonly byte NOTE_OFF = 0x80;
        public static readonly byte NOTE_ON = 0x90;
        public static readonly byte POLY_TOUCH = 0xA0;
        public static readonly byte CONTROL = 0xB0;
        public static readonly byte PROGRAM = 0xC0;
        public static readonly byte CHANNEL_TOUCH = 0xD0;
        public static readonly byte PITCH = 0xE0;

        public static readonly Dictionary<byte, string> NOTE_MAP = new Dictionary<byte, string>()
        {
            { 0x00, "B-2" },
            { 0x01, "C-1" },
            { 0x02, "C#-1" },
            { 0x03, "D-1" },
            { 0x04, "D#-1" },
            { 0x05, "E-1" },
            { 0x06, "F-1" },
            { 0x07, "F#-1" },
            { 0x08, "G-1" },
            { 0x09, "G#-1" },
            { 0x0A, "A-1" },
            { 0x0B, "A#-1" },
            { 0x0C, "B-1" },
            { 0x0D, "C0" },
            { 0x0E, "C#0" },
            { 0x0F, "D0" },
            { 0x10, "D#0" },
            { 0x11, "E0" },
            { 0x12, "F0" },
            { 0x13, "F#0" },
            { 0x14, "G0" },
            { 0x15, "G#0" },
            { 0x16, "A#0" },
            { 0x17, "B0" },
            { 0x18, "C1" },
            { 0x19, "C#1" },
            { 0x1A, "D1" },
            { 0x1B, "D#1" },
            { 0x1C, "E1" },
            { 0x1D, "F1" },
            { 0x1E, "F#1" },
            { 0x1F, "G1" },
            { 0x20, "G#1" },
            { 0x21, "A1" },
            { 0x22, "A#1" },
            { 0x23, "B1" },
            { 0x24, "C2" },
            { 0x25, "C#2" },
            { 0x26, "D2" },
            { 0x27, "D#2" },
            { 0x28, "E2" },
            { 0x29, "F2" },
            { 0x2A, "F#2" },
            { 0x2B, "G2" },
            { 0x2C, "G#2" },
            { 0x2D, "A2" },
            { 0x2E, "A#2" },
            { 0x2F, "B2" },
            { 0x30, "C3" },
            { 0x31, "C#3" },
            { 0x32, "D3" },
            { 0x33, "D#3" },
            { 0x34, "E3" },
            { 0x35, "F3" },
            { 0x36, "F#3" },
            { 0x37, "G3" },
            { 0x38, "G#3" },
            { 0x39, "A3" },
            { 0x3A, "A#3" },
            { 0x3B, "B3" },
            { 0x3C, "C4" },
            { 0x3D, "C#4" },
            { 0x3E, "D4" },
            { 0x3F, "D#4" },
            { 0x40, "E4" },
            { 0x41, "F4" },
            { 0x42, "F#4" },
            { 0x43, "G4" },
            { 0x44, "G#4" },
            { 0x45, "A4" },
            { 0x46, "A#4" },
            { 0x47, "B4" },
            { 0x48, "C5" },
            { 0x49, "C#5" },
            { 0x4A, "D5" },
            { 0x4B, "D#5" },
            { 0x4C, "E5" },
            { 0x4D, "F5" },
            { 0x4E, "F#5" },
            { 0x4F, "G5" },
            { 0x50, "G#5" },
            { 0x51, "A5" },
            { 0x52, "A#5" },
            { 0x53, "B5" },
            { 0x54, "C6" },
            { 0x55, "C#6" },
            { 0x56, "D6" },
            { 0x57, "D#6" },
            { 0x58, "E6" },
            { 0x59, "F6" },
            { 0x5A, "F#6" },
            { 0x5B, "G6" },
            { 0x5C, "G#6" },
            { 0x5D, "A6" },
            { 0x5E, "A#6" },
            { 0x5F, "B6" },
            { 0x60, "C7" },
            { 0x61, "C#7" },
            { 0x62, "D7" },
            { 0x63, "D#7" },
            { 0x64, "E7" },
            { 0x65, "F7" },
            { 0x66, "F#7" },
            { 0x67, "G7" },
            { 0x68, "G#7" },
            { 0x69, "A7" },
            { 0x6A, "A#7" },
            { 0x6B, "B7" },
            { 0x6C, "C8" },
            { 0x6D, "C#8" },
            { 0x6E, "D8" },
            { 0x6F, "D#8" },
            { 0x70, "E8" },
            { 0x71, "F8" },
            { 0x72, "F#8" },
            { 0x73, "G8" },
            { 0x74, "G#8" },
            { 0x75, "A8" },
            { 0x76, "A#8" },
            { 0x77, "B8" },
            { 0x78, "C9" },
            { 0x79, "C#9" },
            { 0x7A, "D9" },
            { 0x7B, "D#9" },
            { 0x7C, "E9" },
            { 0x7D, "F9" },
            { 0x7E, "F#9" },
            { 0x7F, "G9" }
        };

        public static readonly Dictionary<byte, string> INSTRUMENT_MAP = new Dictionary<byte, string>()
        {
            { 0x00, "Acoustic Grand Piano" },
            { 0x01, "Bright Acoustic Piano" },
            { 0x02, "Electric Grand Piano" },
            { 0x03, "Honky-Tonk Piano" },
            { 0x04, "Electric Piano 1" },
            { 0x05, "Electric Piano 2" },
            { 0x06, "Harpsichord" },
            { 0x07, "Clavi" },
            { 0x08, "Celesta" },
            { 0x09, "Glockenspiel" },
            { 0x0A, "Music Box" },
            { 0x0B, "Vibraphone" },
            { 0x0C, "Marimba" },
            { 0x0D, "Xylophone" },
            { 0x0E, "Tubular Bells" },
            { 0x0F, "Dulcimer" },
            { 0x10, "Drawbar Organ" },
            { 0x11, "Percussive Organ" },
            { 0x12, "Rock Organ" },
            { 0x13, "Church Organ" },
            { 0x14, "Reed Organ" },
            { 0x15, "Accordion" },
            { 0x16, "Harmonica" },
            { 0x17, "Tango Accordion" },
            { 0x18, "Acoustic Guitar (nylon)" },
            { 0x19, "Acoustic Guitar (steel)" },
            { 0x1A, "Electric Guitar (jazz)" },
            { 0x1B, "Electric Guitar (clean)" },
            { 0x1C, "Electric Guitar (muted)" },
            { 0x1D, "Overdriven Guitar" },
            { 0x1E, "Distortion Guitar" },
            { 0x1F, "Guitar Harmonics" },
            { 0x20, "Acoustic Bass" },
            { 0x21, "Electric Bass (finger)" },
            { 0x22, "Electric Bass (pick)" },
            { 0x23, "Fretless Bass" },
            { 0x24, "Slap Bass 1" },
            { 0x25, "Slap Bass 2" },
            { 0x26, "Synth Bass 1" },
            { 0x27, "Synth Bass 2" },
            { 0x28, "Violin" },
            { 0x29, "Viola" },
            { 0x2A, "Cello" },
            { 0x2B, "Contrabass" },
            { 0x2C, "Tremolo Strings" },
            { 0x2D, "Pizzicato Strings" },
            { 0x2E, "Orchestral Harp" },
            { 0x2F, "Timpani" },
            { 0x30, "String Ensemble 1" },
            { 0x31, "String Ensemble 2" },
            { 0x32, "SynthStrings 1" },
            { 0x33, "SynthStrings 2" },
            { 0x34, "Choir Aahs" },
            { 0x35, "Voice Oohs" },
            { 0x36, "Synth Voice" },
            { 0x37, "Orchestra Hit" },
            { 0x38, "Trumpet" },
            { 0x39, "Trombone" },
            { 0x3A, "Tuba" },
            { 0x3B, "Muted Trumpet" },
            { 0x3C, "French Horn" },
            { 0x3D, "Brass Section" },
            { 0x3E, "SynthBrass 1" },
            { 0x3F, "SynthBrass 2" },
            { 0x40, "Soprano Sax" },
            { 0x41, "Alto Sax" },
            { 0x42, "Tenor Sax" },
            { 0x43, "Baritone Sax" },
            { 0x44, "Oboe" },
            { 0x45, "English Horn" },
            { 0x46, "Bassoon" },
            { 0x47, "Clarinet" },
            { 0x48, "Piccolo" },
            { 0x49, "Flute" },
            { 0x4A, "Recorder" },
            { 0x4B, "Pan Flute" },
            { 0x4C, "Blown Bottle" },
            { 0x4D, "Shakuhachi" },
            { 0x4E, "Whistle" },
            { 0x4F, "Ocarina" },
            { 0x50, "Lead 1 (Square)" },
            { 0x51, "Lead 2 (Sawtooth)" },
            { 0x52, "Lead 3 (Calliope)" },
            { 0x53, "Lead 4 (Chiff)" },
            { 0x54, "Lead 5 (Charang)" },
            { 0x55, "Lead 6 (Voice)" },
            { 0x56, "Lead 7 (Fifths)" },
            { 0x57, "Lead 8 (Bass + Lead)" },
            { 0x58, "Pad 1 (New Age)" },
            { 0x59, "Pad 2 (Warm)" },
            { 0x5A, "Pad 3 (Polysynth)" },
            { 0x5B, "Pad 4 (Choir)" },
            { 0x5C, "Pad 5 (Bowed)" },
            { 0x5D, "Pad 6 (Metallic)" },
            { 0x5E, "Pad 7 (Halo)" },
            { 0x5F, "Pad 8 (Sweep)" },
            { 0x60, "FX 1 (Rain)" },
            { 0x61, "FX 2 (Soundtrack)" },
            { 0x62, "FX 3 (Crystal)" },
            { 0x63, "FX 4 (Atmosphere)" },
            { 0x64, "FX 5 (Brightness)" },
            { 0x65, "FX 6 (Goblins)" },
            { 0x66, "FX 7 (Echoes)" },
            { 0x67, "FX 8 (Sci-Fi)" },
            { 0x68, "Sitar" },
            { 0x69, "Banjo" },
            { 0x6A, "Shamisen" },
            { 0x6B, "Koto" },
            { 0x6C, "Kalimba" },
            { 0x6D, "Bag Pipe" },
            { 0x6E, "Fiddle" },
            { 0x6F, "Shanai" },
            { 0x70, "Tinkle Bell" },
            { 0x71, "Agogo" },
            { 0x72, "Steel Drums" },
            { 0x73, "Woodblock" },
            { 0x74, "Taiko Drum" },
            { 0x75, "Melodic Tom" },
            { 0x76, "Synth Drum" },
            { 0x77, "Reverse Cymbal" },
            { 0x78, "Guitar Fret Noise" },
            { 0x79, "Breath Noise" },
            { 0x7A, "Seashore" },
            { 0x7B, "Bird Tweet" },
            { 0x7C, "Telephone Ring" },
            { 0x7D, "Helicopter" },
            { 0x7E, "Applause" },
            { 0x7F, "Gunshot" }
        };
    }
}
